/**
 * JSON Schema in one form, so that schemas generated by zod and by Effect can
 * be compared, as core/tests/contract.test.ts compares them. Dropped:
 * `$schema`, `pattern` (behavior is compared there instead of regex spelling)
 * and `additionalProperties` (both accept and strip unknown keys). Type lists
 * become `anyOf`, and `const` becomes a one-value `enum`.
 */

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };

export function normalizeJsonSchema(node: unknown): Json {
  return normalize(node as Json);
}

function normalize(node: Json): Json {
  if (Array.isArray(node)) return node.map(normalize);
  if (node === null || typeof node !== "object") return node;
  const { $schema, pattern, additionalProperties, ...rest } = node;
  const out: Record<string, Json> = {};
  for (const [key, value] of Object.entries(rest)) out[key] = normalize(value);
  const type = out["type"];
  if (Array.isArray(type)) {
    const { type: _, description, ...facets } = out;
    return normalize({
      ...(description === undefined ? {} : { description }),
      anyOf: type.map((t) =>
        t === "null" ? { type: t } : { type: t, ...facets },
      ),
    });
  }
  if ("const" in out) {
    const { const: value, ...others } = out;
    return { ...others, enum: [value ?? null] };
  }
  return out;
}
