# fly.toml app configuration file generated for allthingsweb-sync on 2025-03-08T11:07:12-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'allthingsweb-sync'
primary_region = 'sjc'

[build]
  image = 'registry.hub.docker.com/rocicorp/zero:0.16.2025022602'

[env]
  LOG_LEVEL = 'debug'

[[mounts]]
  source = 'sqlite_db'
  destination = '/data'

[http_service]
  internal_port = 4848
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
