import { Context, Duration, Effect, Layer } from "effect";
import { HttpClient, HttpClientRequest } from "effect/http";
import { approvalToken } from "../approval.ts";
import { siteOrigin, StudioRefused } from "./publish.ts";
import {
  type CalendarFields,
  LumaWrite,
  type LumaWriteError,
  type ManagedCalendar,
} from "./write.ts";

/**
 * The Luma calendar (luma.com/allthingsweb) in the brand: what its page
 * says, set through Luma's API (`calendars/update`) in two steps, as
 * publishing is.
 *
 * What it should say is written here, once: the name, allthings; the two
 * sentences that are the whole pitch (brand/foundations.md, "Who we are");
 * the slash's color as its tint (Bridge); the site; the channels the
 * site's footer lists (web/src/links.ts; tests/luma-calendar.test.ts holds
 * them to it); and the a/ app icon as its avatar (app/public/brand,
 * generated by brand/marks). Its address on Luma changes only when asked
 * for (`slug`): links to the old one are everywhere.
 *
 * - `prepare` reads the calendar and says each field it would change, from
 *   what to what, and the approval token for exactly that: the first 16
 *   hex digits of the SHA-256 of the calendar's id, the changes and the
 *   avatar's SHA-256, as canonical JSON. The avatar is a change unless
 *   Luma's is the same image, byte for byte.
 * - `approve` takes that token, works the changes out again and goes on
 *   only if they hash the same. It uploads the avatar to Luma's CDN when it
 *   changes, sends one update with the changed fields, and reads the
 *   calendar back to check each took.
 *
 * Luma's API can't set the calendar's cover or its social preview image;
 * those are an organizer's, in the calendar's settings (brand/covers and
 * brand/og have the files).
 */

/** The two sentences, as the foundations set them. */
export const calendarSentences = [
  "Evenings for people who build software.",
  "In the neighborhoods of San Francisco.",
] as const;

/** What the calendar's page should say, as `calendars/update` names it. */
export const wantedCalendar = {
  name: "allthings",
  description: calendarSentences.join(" "),
  // Bridge: the slash on light grounds (brand/all-things.tokens.json).
  tint_color: "#C0362C",
  website: siteOrigin,
  twitter_handle: "allthingswebdev",
  youtube_handle: "allthingsweb-dev",
  linkedin_handle: "https://www.linkedin.com/company/all-things-web-dev/",
} as const satisfies CalendarFields;

/** The calendar's avatar: the a/ app icon on Night, 512 px. */
export const avatarFile = new URL(
  "../../../app/public/brand/icon-512.png",
  import.meta.url,
);

/** A field the update changes, from what Luma has to what it should say. */
export interface CalendarChange {
  readonly field: keyof CalendarFields;
  readonly from: string | null;
  readonly to: string;
}

export interface PreparedCalendar {
  readonly calendarId: string;
  readonly url: string;
  readonly changes: ReadonlyArray<CalendarChange>;
  readonly avatar: {
    readonly file: string;
    readonly sha256: string;
    /** Luma's avatar now. */
    readonly current: string | null;
    /** Whether Luma's is this image already. */
    readonly same: boolean;
  };
  /** What only the calendar's settings can change, as Luma has it now. */
  readonly byHand: {
    readonly coverImageUrl: string | null;
    readonly socialImageUrl: string | null;
  };
  readonly token: string;
}

export type CalendarFailure = StudioRefused | LumaWriteError;

export interface CalendarShape {
  readonly prepare: (options: {
    readonly slug?: string;
  }) => Effect.Effect<PreparedCalendar, CalendarFailure>;
  readonly approve: (
    token: string,
    options: { readonly slug?: string },
  ) => Effect.Effect<PreparedCalendar, CalendarFailure>;
}

const refuse = (reason: string) => Effect.fail(new StudioRefused({ reason }));

/**
 * A field's value as Luma compares: handles without "@" or their site's
 * address, URLs without a trailing slash, colors in lowercase. Luma
 * stores some fields its own way, and the same value must never read as a
 * change.
 */
export function comparable(
  field: keyof CalendarFields,
  value: string | null,
): string {
  const text = (value ?? "").trim();
  if (field === "tint_color") return text.toLowerCase();
  if (field === "website") return text.toLowerCase().replace(/\/+$/, "");
  if (field === "linkedin_handle") {
    return text
      .toLowerCase()
      .replace(/^https?:\/\/(www\.)?linkedin\.com/, "")
      .replace(/\/+$/, "");
  }
  if (field.endsWith("_handle")) {
    return text
      .toLowerCase()
      .replace(
        /^https?:\/\/(www\.)?(x|twitter|youtube|instagram|tiktok)\.com\//,
        "",
      )
      .replace(/^@/, "")
      .replace(/\/+$/, "");
  }
  return text;
}

/** The calendar's fields that differ from what they should say. */
export function calendarChanges(
  calendar: ManagedCalendar,
  wanted: CalendarFields,
): ReadonlyArray<CalendarChange> {
  return (Object.keys(wanted) as Array<keyof CalendarFields>).flatMap(
    (field) => {
      const to = wanted[field];
      if (to === undefined || to === null) return [];
      const from =
        field in calendar ? calendar[field as keyof ManagedCalendar] : null;
      const current = typeof from === "string" ? from : null;
      return comparable(field, current) === comparable(field, to)
        ? []
        : [{ field, from: current, to }];
    },
  );
}

const hex = (bytes: ArrayBuffer) =>
  [...new Uint8Array(bytes)]
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");

const sha256 = (bytes: Uint8Array) =>
  Effect.promise(() =>
    crypto.subtle.digest("SHA-256", new Uint8Array(bytes)).then(hex),
  );

/** The longest reading Luma's avatar now may take. */
const avatarReadTimeout = Duration.seconds(20);

/** A slug Luma takes: lowercase letters, digits and single hyphens. */
const slugShape = /^[a-z0-9]+(-[a-z0-9]+)*$/;

const make = Effect.gen(function* () {
  const luma = yield* LumaWrite;
  const client = yield* HttpClient.HttpClient;

  /** The bytes of the avatar Luma shows now, when it is on Luma's CDN. */
  const currentAvatar = (url: string | null) => {
    if (url === null || !url.startsWith("https://images.lumacdn.com/")) {
      return Effect.succeed(null);
    }
    return client.execute(HttpClientRequest.get(url)).pipe(
      Effect.flatMap((response) =>
        response.status === 200 ? response.arrayBuffer : Effect.succeed(null),
      ),
      Effect.map((buffer) => (buffer === null ? null : new Uint8Array(buffer))),
      Effect.timeout(avatarReadTimeout),
      // Unreadable or slow is only "not known to be the same": it is
      // uploaded again.
      Effect.catch(() => Effect.succeed(null)),
    );
  };

  const prepare = (options: { readonly slug?: string }) =>
    Effect.gen(function* () {
      if (options.slug !== undefined && !slugShape.test(options.slug)) {
        return yield* refuse(
          `A calendar's address is lowercase letters, digits and hyphens: ${options.slug}`,
        );
      }
      const calendar = yield* luma.getCalendar();
      const changes = calendarChanges(calendar, {
        ...wantedCalendar,
        ...(options.slug === undefined ? {} : { slug: options.slug }),
      });
      const png = new Uint8Array(
        yield* Effect.promise(() => Bun.file(avatarFile).arrayBuffer()),
      );
      const digest = yield* sha256(png);
      const now = yield* currentAvatar(calendar.avatar_url);
      const same = now !== null && (yield* sha256(now)) === digest;
      const all: ReadonlyArray<CalendarChange> = same
        ? changes
        : [
            ...changes,
            {
              field: "avatar_url",
              from: calendar.avatar_url,
              to: `app/public/brand/icon-512.png (sha256 ${digest})`,
            },
          ];
      return {
        calendarId: calendar.id,
        url: calendar.url,
        changes: all,
        avatar: {
          file: Bun.fileURLToPath(avatarFile),
          sha256: digest,
          current: calendar.avatar_url,
          same,
        },
        byHand: {
          coverImageUrl: calendar.cover_image_url,
          socialImageUrl: calendar.social_image_url,
        },
        token: yield* approvalToken({
          calendarId: calendar.id,
          changes: all,
          avatar: digest,
        }),
        png,
      };
    });

  const approve = (token: string, options: { readonly slug?: string }) =>
    Effect.gen(function* () {
      const { png, ...prepared } = yield* prepare(options);
      if (prepared.token !== token) {
        return yield* refuse(
          `What would change has changed since ${token} was approved: it is now ${prepared.token}. Read it again with --dry-run, and approve that.`,
        );
      }
      if (prepared.changes.length === 0) {
        return yield* refuse("Nothing to change: the calendar says it all.");
      }
      const avatarUrl = prepared.avatar.same
        ? undefined
        : yield* luma.uploadImage(png, "image/png");
      const fields: Record<string, string> = {};
      for (const change of prepared.changes) {
        fields[change.field] =
          change.field === "avatar_url" ? (avatarUrl ?? change.to) : change.to;
      }
      yield* luma.updateCalendar(prepared.calendarId, fields);
      const after = yield* luma.getCalendar();
      const missed = prepared.changes.filter((change) =>
        // The avatar took only if Luma shows exactly the one uploaded.
        change.field === "avatar_url"
          ? after.avatar_url !== avatarUrl
          : comparable(change.field, after[change.field] ?? null) !==
            comparable(change.field, change.to),
      );
      if (missed.length > 0) {
        return yield* refuse(
          `Luma took the update, but these don't read as sent: ${missed
            .map(
              (change) =>
                `${change.field} is ${String(after[change.field] ?? null)}`,
            )
            .join("; ")}.`,
        );
      }
      return prepared;
    });

  return Calendar.of({
    prepare: (options) =>
      Effect.map(prepare(options), ({ png: _png, ...prepared }) => prepared),
    approve,
  });
});

export class Calendar extends Context.Service<Calendar, CalendarShape>()(
  "allthings/Calendar",
) {
  /** Needs an `HttpClient`, for reading Luma's avatar now. */
  static readonly layer = Layer.effect(Calendar, make);
}
