import { Effect, Schema } from "effect";
import { SqlClient } from "effect/sql/SqlClient";
import type { SqlError } from "effect/sql/SqlError";

/**
 * A database's schema as sorted lines of text, read from the catalog, so two
 * databases can be compared exactly and their differences read as a diff.
 *
 * It covers the schemas the app's tables live in: `public`; `neon_auth`,
 * whose `users_sync` table Neon Auth owns and the app references; and
 * `planning`, the organizers' private planning (migrations/0011_planning.ts). Each line is
 * one object: a relation (with its row security and options), a column (its
 * position among the table's live columns, type, nullability, default,
 * identity, generation and collation), a constraint (primary, unique, check
 * and foreign keys with their actions, as Postgres prints them), an index (its
 * full definition, and whether it is valid), an enum (labels in order), a domain or other type, a
 * sequence, a view, a trigger, a row security policy, a routine or a comment.
 *
 * Owners and grants are left out: they belong to the environment (Neon's
 * roles), not to the schema the migrations create. So are the NOT NULL
 * constraints Postgres 18 catalogs: the column lines say which columns are
 * not null, and production (17) and PGlite (18) read the same that way.
 */

/** The schemas compared. */
export const schemas: ReadonlyArray<string> = [
  "public",
  "neon_auth",
  "planning",
];

/**
 * Objects the platform keeps in those schemas that no migration creates, each
 * matched by the start of its line, with why it is not the app's.
 */
export const platformObjects: ReadonlyArray<{
  readonly prefix: string;
  readonly reason: string;
}> = [
  {
    prefix: "routine public.show_db_tree() ",
    reason:
      "A schema-browsing helper production has had since the Neon project was created. No migration creates it and nothing calls it.",
  },
];

const query = `
WITH ns AS (
  SELECT oid, nspname FROM pg_catalog.pg_namespace WHERE nspname IN (${schemas.map((name) => `'${name}'`).join(", ")})
), rel AS (
  SELECT c.oid, c.relname, c.relkind, c.relpersistence, c.relrowsecurity,
    c.relforcerowsecurity, c.relreplident, c.reloptions, ns.nspname
  FROM pg_catalog.pg_class c JOIN ns ON c.relnamespace = ns.oid
  WHERE c.relkind IN ('r', 'p', 'v', 'm', 'S', 'f')
)
SELECT line FROM (
  SELECT format('relation %I.%I kind=%s persistence=%s rls=%s force_rls=%s replica_identity=%s options=%s',
    nspname, relname, relkind, relpersistence, relrowsecurity, relforcerowsecurity,
    relreplident, coalesce(array_to_string(reloptions, ','), '')) AS line
  FROM rel
  UNION ALL
  SELECT format('column %I.%I #%s %I %s%s%s%s%s%s',
    r.nspname, r.relname,
    lpad((row_number() OVER (PARTITION BY a.attrelid ORDER BY a.attnum))::text, 3, '0'),
    a.attname, pg_catalog.format_type(a.atttypid, a.atttypmod),
    CASE WHEN a.attnotnull THEN ' not null' ELSE '' END,
    CASE WHEN a.attgenerated = '' THEN coalesce(' default ' || pg_catalog.pg_get_expr(d.adbin, d.adrelid), '') ELSE '' END,
    CASE a.attidentity WHEN 'a' THEN ' generated always as identity' WHEN 'd' THEN ' generated by default as identity' ELSE '' END,
    CASE WHEN a.attgenerated = 's' THEN ' generated always as (' || pg_catalog.pg_get_expr(d.adbin, d.adrelid) || ') stored' ELSE '' END,
    CASE WHEN a.attcollation <> t.typcollation THEN ' collate ' || quote_ident(co.collname) ELSE '' END)
  FROM pg_catalog.pg_attribute a
  JOIN rel r ON a.attrelid = r.oid
  JOIN pg_catalog.pg_type t ON t.oid = a.atttypid
  LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
  LEFT JOIN pg_catalog.pg_collation co ON co.oid = a.attcollation
  WHERE a.attnum > 0 AND NOT a.attisdropped
  UNION ALL
  SELECT format('constraint %I.%I %I %s', r.nspname, r.relname, c.conname, pg_catalog.pg_get_constraintdef(c.oid))
  FROM pg_catalog.pg_constraint c JOIN rel r ON c.conrelid = r.oid
  WHERE c.contype <> 'n'
  UNION ALL
  SELECT format('index %I.%I %s%s', r.nspname, r.relname, pg_catalog.pg_get_indexdef(i.indexrelid),
    CASE WHEN i.indisvalid THEN '' ELSE ' invalid' END)
  FROM pg_catalog.pg_index i JOIN rel r ON i.indrelid = r.oid
  UNION ALL
  SELECT format('enum %I.%I (%s)', ns.nspname, t.typname,
    string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder))
  FROM pg_catalog.pg_type t
  JOIN ns ON t.typnamespace = ns.oid
  JOIN pg_catalog.pg_enum e ON e.enumtypid = t.oid
  GROUP BY ns.nspname, t.typname
  UNION ALL
  SELECT format('type %I.%I kind=%s base=%s not_null=%s default=%s', ns.nspname, t.typname,
    t.typtype, pg_catalog.format_type(t.typbasetype, t.typtypmod), t.typnotnull, t.typdefault)
  FROM pg_catalog.pg_type t JOIN ns ON t.typnamespace = ns.oid
  WHERE t.typtype IN ('d', 'r', 'm')
    OR (t.typtype = 'c' AND (SELECT c.relkind FROM pg_catalog.pg_class c WHERE c.oid = t.typrelid) = 'c')
  UNION ALL
  SELECT format('constraint %I.%I %I %s', ns.nspname, t.typname, c.conname, pg_catalog.pg_get_constraintdef(c.oid))
  FROM pg_catalog.pg_constraint c
  JOIN pg_catalog.pg_type t ON c.contypid = t.oid
  JOIN ns ON t.typnamespace = ns.oid
  UNION ALL
  SELECT format('sequence %I.%I %s start=%s increment=%s min=%s max=%s cache=%s cycle=%s',
    r.nspname, r.relname, pg_catalog.format_type(s.seqtypid, NULL), s.seqstart,
    s.seqincrement, s.seqmin, s.seqmax, s.seqcache, s.seqcycle)
  FROM pg_catalog.pg_sequence s JOIN rel r ON s.seqrelid = r.oid
  UNION ALL
  SELECT format('view %I.%I %s', r.nspname, r.relname,
    regexp_replace(pg_catalog.pg_get_viewdef(r.oid), '\\s+', ' ', 'g'))
  FROM rel r WHERE r.relkind IN ('v', 'm')
  UNION ALL
  SELECT format('trigger %s', pg_catalog.pg_get_triggerdef(tg.oid))
  FROM pg_catalog.pg_trigger tg JOIN rel r ON tg.tgrelid = r.oid
  WHERE NOT tg.tgisinternal
  UNION ALL
  SELECT format('policy %I.%I %I %s', r.nspname, r.relname, p.polname,
    pg_catalog.md5(concat_ws(' ', p.polcmd, p.polpermissive, p.polroles::text,
      pg_catalog.pg_get_expr(p.polqual, p.polrelid),
      pg_catalog.pg_get_expr(p.polwithcheck, p.polrelid))))
  FROM pg_catalog.pg_policy p JOIN rel r ON p.polrelid = r.oid
  UNION ALL
  SELECT format('routine %I.%I(%s) %s', ns.nspname, p.proname,
    pg_catalog.pg_get_function_identity_arguments(p.oid),
    pg_catalog.md5(pg_catalog.pg_get_functiondef(p.oid)))
  FROM pg_catalog.pg_proc p JOIN ns ON p.pronamespace = ns.oid
  WHERE p.prokind IN ('f', 'p')
  UNION ALL
  SELECT format('comment %I.%I%s %s', r.nspname, r.relname,
    CASE WHEN d.objsubid = 0 THEN '' ELSE '.' || quote_ident((
      SELECT a.attname FROM pg_catalog.pg_attribute a
      WHERE a.attrelid = r.oid AND a.attnum = d.objsubid)) END,
    quote_literal(d.description))
  FROM pg_catalog.pg_description d
  JOIN rel r ON d.objoid = r.oid AND d.classoid = 'pg_catalog.pg_class'::regclass
) lines
ORDER BY line COLLATE "C"`;

const Line = Schema.Struct({ line: Schema.String });

/** Whether `line` describes an object the platform, not a migration, made. */
const isPlatformObject = (line: string): boolean =>
  platformObjects.some(({ prefix }) => line.startsWith(prefix));

/** The schema of the database `SqlClient` reaches, as sorted lines. */
export const snapshot: Effect.Effect<
  ReadonlyArray<string>,
  SqlError | Schema.SchemaError,
  SqlClient
> = Effect.gen(function* () {
  const sql = yield* SqlClient;
  const rows = yield* sql.unsafe(query);
  const lines = yield* Schema.decodeUnknownEffect(Schema.Array(Line))(rows);
  return lines
    .map(({ line }) => line)
    .filter((line) => !isPlatformObject(line));
});

/** What one snapshot has that another lacks, both ways. */
export interface SchemaDiff {
  /** Lines only the expected schema has. */
  readonly missing: ReadonlyArray<string>;
  /** Lines only the actual schema has. */
  readonly unexpected: ReadonlyArray<string>;
}

/** How `actual` differs from `expected`; both lists are empty when they match. */
export function diff(
  expected: ReadonlyArray<string>,
  actual: ReadonlyArray<string>,
): SchemaDiff {
  const inExpected = new Set(expected);
  const inActual = new Set(actual);
  return {
    missing: expected.filter((line) => !inActual.has(line)),
    unexpected: actual.filter((line) => !inExpected.has(line)),
  };
}

/** Whether a diff found no difference. */
export const isEmpty = ({ missing, unexpected }: SchemaDiff): boolean =>
  missing.length === 0 && unexpected.length === 0;

/** A diff as unified-diff-style lines: `-` expected only, `+` actual only. */
export const format = ({ missing, unexpected }: SchemaDiff): string =>
  [
    ...missing.map((line) => `- ${line}`),
    ...unexpected.map((line) => `+ ${line}`),
  ].join("\n");
