# fly.toml app configuration file generated for allthingsweb-cms on 2024-08-10T12:47:31-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'allthingsweb-cms'
primary_region = 'sjc'

[build]
  [build.args]
    GO_VERSION = '1.22.6'

[deploy]
  strategy = "rolling"

[env]
  PORT = '8080'

# Do not force https as internal fly proxy doesn't do https
[http_service]
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  destination = "/pb_data"
  source = "allthingsweb_pb_data"
