# fly.toml app configuration file generated for allthingsweb-sync on 2025-02-20T14:40:07-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'allthingsweb-sync'
primary_region = 'sjc'

[build]
  image = 'electricsql/electric:latest'

[env]
  ELECTRIC_DATABASE_USE_IPV6 = 'true'

[http_service]
  internal_port = 3000
  force_https = true

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '20s'
    method = 'GET'
    path = '/v1/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
