import type { Image } from "@/lib/events";

/**
 * The brand's canonical avatar for a person or host without a photo or logo:
 * the wordmark's open slot, "/_". Generated by brand/marks from the tokens.
 */
export function blankAvatar(name: string): Image {
  return {
    url: "/brand/avatar.png",
    alt: name,
    placeholder: null,
    width: 512,
    height: 512,
  };
}
