import { z } from "zod";

/**
 * Validates the all things/_ design tokens (W3C Design Tokens Community Group
 * format) and generates the CSS theme and typed constants from them.
 */

const unit = z.number().min(0).max(1);
const colorToken = z.object({
  $value: z.object({
    colorSpace: z.literal("srgb"),
    components: z.tuple([unit, unit, unit]),
  }),
  $description: z.string(),
});
const px = z.object({ value: z.number(), unit: z.literal("px") });
/** A `{group.name}` reference into one token group; names are checked below. */
const reference = (group: "color" | "font") =>
  z
    .string()
    .regex(
      new RegExp(`^\\{${group}\\.[A-Za-z]+\\}$`),
      `Expected a {${group}.name} reference`,
    );
const typeToken = z.object({
  $value: z.object({
    fontFamily: reference("font"),
    fontSize: px,
    fontWeight: z.number().int().min(1).max(1000),
    lineHeight: z.number().positive(),
    letterSpacing: px,
  }),
  $description: z.string(),
  $extensions: z.object({
    "dev.allthings": z.object({
      width: z
        .string()
        .regex(/^\d+%$/)
        .optional(),
      letterSpacingEm: z.number(),
      textTransform: z.literal("uppercase").optional(),
    }),
  }),
});
const contrastPair = z.object({
  text: reference("color"),
  background: reference("color"),
  minLc: z.number().positive(),
  use: z.string(),
});

export const tokenFileSchema = z
  .object({
    $description: z.string(),
    color: z.object({ $type: z.literal("color") }).catchall(colorToken),
    font: z.object({
      $type: z.literal("fontFamily"),
      display: z.object({
        $value: z.array(z.string()).min(1),
        $description: z.string(),
      }),
      mono: z.object({
        $value: z.array(z.string()).min(1),
        $description: z.string(),
      }),
    }),
    type: z.object({ $type: z.literal("typography") }).catchall(typeToken),
    layout: z.object({
      $type: z.literal("dimension"),
      gutter: z.object({ $value: px, $description: z.string() }),
      margin: z.object({ $value: px, $description: z.string() }),
    }),
    motion: z.object({
      cursorBlink: z.object({
        $type: z.literal("duration"),
        $value: z.object({
          value: z.number().positive(),
          unit: z.literal("ms"),
        }),
        $description: z.string(),
      }),
    }),
    $extensions: z.object({
      "dev.allthings": z.object({
        gridColumns: z.number().int().positive(),
        contrast: z.array(contrastPair).min(1),
      }),
    }),
  })
  .superRefine((file, ctx) => {
    const defined = (group: "color" | "font", ref: string) => {
      const name = referencedName(ref);
      return name !== "$type" && Object.hasOwn(file[group], name);
    };
    for (const [role, token] of Object.entries(file.type)) {
      if (typeof token === "string") continue;
      if (!defined("font", token.$value.fontFamily)) {
        ctx.addIssue({
          code: "custom",
          path: ["type", role, "$value", "fontFamily"],
          message: `Unknown font ${token.$value.fontFamily}`,
        });
      }
    }
    file.$extensions["dev.allthings"].contrast.forEach((pair, index) => {
      for (const side of ["text", "background"] as const) {
        if (!defined("color", pair[side])) {
          ctx.addIssue({
            code: "custom",
            path: ["$extensions", "dev.allthings", "contrast", index, side],
            message: `Unknown color ${pair[side]}`,
          });
        }
      }
    });
  });

export type TokenFile = z.infer<typeof tokenFileSchema>;

const header =
  "Generated by scripts/generate-brand.ts from src/brand/all-things.tokens.json. Do not edit.";

function kebab(name: string): string {
  return name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
}

function toHex([r, g, b]: readonly [number, number, number]): string {
  return `#${[r, g, b]
    .map((c) =>
      Math.round(c * 255)
        .toString(16)
        .padStart(2, "0"),
    )
    .join("")
    .toUpperCase()}`;
}

function cssFontFamily(families: readonly string[]): string {
  return families
    .map((family) => (family.includes(" ") ? `"${family}"` : family))
    .join(", ");
}

/** Every color token, by name, as an uppercase hex string. */
export function colorHexes(tokens: TokenFile): Record<string, string> {
  return Object.fromEntries(
    Object.entries(tokens.color)
      .filter(
        (entry): entry is [string, z.infer<typeof colorToken>] =>
          entry[0] !== "$type",
      )
      .map(([name, token]) => [name, toHex(token.$value.components)]),
  );
}

/** Resolves a `{group.name}` reference to the referenced token's name. */
export function referencedName(ref: string): string {
  return ref.slice(1, -1).split(".")[1]!;
}

function typeRoles(tokens: TokenFile) {
  return Object.entries(tokens.type)
    .filter(
      (entry): entry is [string, z.infer<typeof typeToken>] =>
        entry[0] !== "$type",
    )
    .map(([name, token]) => {
      const ext = token.$extensions["dev.allthings"];
      return {
        name,
        family: referencedName(token.$value.fontFamily),
        size: token.$value.fontSize.value,
        weight: token.$value.fontWeight,
        lineHeight: token.$value.lineHeight,
        letterSpacingEm: ext.letterSpacingEm,
        width: ext.width,
        uppercase: ext.textTransform === "uppercase",
      };
    });
}

/** CSS scoped to [data-brand="allthings"], so the current site is unaffected. */
export function generateCss(tokens: TokenFile): string {
  const scope = '[data-brand="allthings"]';
  const colors = Object.entries(colorHexes(tokens)).map(
    ([name, hex]) => `  --at-color-${kebab(name)}: ${hex};`,
  );
  const fonts = (["display", "mono"] as const).map(
    (name) =>
      `  --at-font-${name}: ${cssFontFamily(tokens.font[name].$value)};`,
  );
  const ext = tokens.$extensions["dev.allthings"];
  const layout = [
    `  --at-grid-columns: ${ext.gridColumns};`,
    `  --at-grid-gutter: ${tokens.layout.gutter.$value.value}px;`,
    `  --at-page-margin: ${tokens.layout.margin.$value.value}px;`,
    `  --at-cursor-blink: ${tokens.motion.cursorBlink.$value.value}ms;`,
  ];
  const roles = typeRoles(tokens).map((role) =>
    [
      `${scope} .at-type-${kebab(role.name)} {`,
      `  font-family: var(--at-font-${role.family});`,
      `  font-size: ${role.size}px;`,
      `  font-weight: ${role.weight};`,
      `  line-height: ${role.lineHeight};`,
      `  letter-spacing: ${role.letterSpacingEm}em;`,
      ...(role.width ? [`  font-stretch: ${role.width};`] : []),
      ...(role.uppercase ? ["  text-transform: uppercase;"] : []),
      "}",
    ].join("\n"),
  );
  return [
    `/* ${header} */`,
    "",
    `${scope} {`,
    ...colors,
    ...fonts,
    ...layout,
    "}",
    "",
    ...roles.flatMap((role) => [role, ""]),
    "@keyframes at-cursor-blink {",
    "  50% {",
    "    opacity: 0;",
    "  }",
    "}",
    "",
    `${scope} .at-cursor {`,
    "  animation: at-cursor-blink var(--at-cursor-blink) steps(1) infinite;",
    "}",
    "",
    "@media (prefers-reduced-motion: reduce) {",
    `  ${scope} .at-cursor {`,
    "    animation: none;",
    "  }",
    "}",
    "",
  ].join("\n");
}

/** Typed constants for code that cannot use CSS, such as OG image templates. */
export function generateTs(tokens: TokenFile): string {
  const colors = Object.entries(colorHexes(tokens))
    .map(([name, hex]) => `  ${name}: "${hex}",`)
    .join("\n");
  const fonts = (["display", "mono"] as const)
    .map((name) => `  ${name}: ${JSON.stringify(tokens.font[name].$value)},`)
    .join("\n");
  const roles = typeRoles(tokens)
    .map(
      (role) =>
        `  ${role.name}: ${JSON.stringify({
          family: role.family,
          size: role.size,
          weight: role.weight,
          lineHeight: role.lineHeight,
          letterSpacingEm: role.letterSpacingEm,
          width: role.width ?? "100%",
          uppercase: role.uppercase,
        })},`,
    )
    .join("\n");
  return [
    `// ${header}`,
    "",
    `export const colors = {\n${colors}\n} as const;`,
    "",
    `export const fonts = {\n${fonts}\n} as const;`,
    "",
    `export const typeRoles = {\n${roles}\n} as const;`,
    "",
    "export type ColorName = keyof typeof colors;",
    "export type TypeRole = keyof typeof typeRoles;",
    "",
  ].join("\n");
}

/** The generated files, formatted the same way as the rest of the code. */
export async function generateFiles(
  tokens: TokenFile,
): Promise<{ "theme.css": string; "tokens.ts": string }> {
  const { format } = await import("prettier");
  return {
    "theme.css": await format(generateCss(tokens), { parser: "css" }),
    "tokens.ts": await format(generateTs(tokens), { parser: "typescript" }),
  };
}
