// Generated by scripts/generate-brand.ts from src/brand/all-things.tokens.json. Do not edit.

export const colors = {
  paper: "#F4F1EC",
  ink: "#141210",
  bridge: "#C0362C",
  bridgeDeep: "#9A2B22",
  violet: "#5B34D6",
  karlText: "#5E5A55",
  karl: "#E6E2DC",
  rulePaper: "#D2CCC3",
  night: "#1C1236",
  nightRaised: "#2A1D4F",
  ruleNight: "#3A2B66",
  mist: "#E3DCF7",
  dusk: "#D9D3E0",
  lavender: "#DACFFF",
  glow: "#FF6A3D",
  white: "#FFFFFF",
} as const;

export const fonts = {
  display: ["Archivo", "sans-serif"],
  mono: ["Geist Mono", "ui-monospace", "monospace"],
} as const;

export const typeRoles = {
  wordmark: {
    family: "display",
    size: 168,
    weight: 800,
    lineHeight: 0.84,
    letterSpacingEm: -0.045,
    width: "112%",
    uppercase: false,
  },
  eventLockup: {
    family: "display",
    size: 72,
    weight: 800,
    lineHeight: 0.9,
    letterSpacingEm: -0.04,
    width: "112%",
    uppercase: false,
  },
  label: {
    family: "display",
    size: 40,
    weight: 700,
    lineHeight: 1,
    letterSpacingEm: -0.01,
    width: "75%",
    uppercase: true,
  },
  lead: {
    family: "display",
    size: 30,
    weight: 500,
    lineHeight: 1.25,
    letterSpacingEm: -0.01,
    width: "100%",
    uppercase: false,
  },
  listName: {
    family: "display",
    size: 21,
    weight: 700,
    lineHeight: 1.3,
    letterSpacingEm: 0,
    width: "100%",
    uppercase: false,
  },
  listPlace: {
    family: "display",
    size: 14,
    weight: 600,
    lineHeight: 1.3,
    letterSpacingEm: 0.06,
    width: "75%",
    uppercase: true,
  },
  body: {
    family: "display",
    size: 18,
    weight: 400,
    lineHeight: 1.55,
    letterSpacingEm: 0,
    width: "100%",
    uppercase: false,
  },
  meta: {
    family: "mono",
    size: 14,
    weight: 500,
    lineHeight: 1.5,
    letterSpacingEm: 0.06,
    width: "100%",
    uppercase: true,
  },
} as const;

export type ColorName = keyof typeof colors;
export type TypeRole = keyof typeof typeRoles;
