import { describe, expect, test } from "bun:test";
import { join } from "node:path";
import { blankAvatar } from "../src/lib/blank-avatar";

describe("the blank avatar", () => {
  test("points at the generated brand asset, named for whoever it stands in for", async () => {
    const avatar = blankAvatar("Erik Peña");
    expect(avatar).toMatchObject({ alt: "Erik Peña", width: 512, height: 512 });
    const file = Bun.file(join(import.meta.dir, "../public", avatar.url));
    expect(await file.exists()).toBe(true);
    // A real PNG, as generated by brand/marks.
    expect([...new Uint8Array(await file.slice(0, 4).arrayBuffer())]).toEqual([
      0x89, 0x50, 0x4e, 0x47,
    ]);
  });
});
