# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'allthingsweb-app'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "get"
  port = 3000
  path = "/healthcheck"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false
  headers = { }

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2

[mounts]
  source = "data"
  destination = "/data"



