"""Each type role's optical inset: how far its letters' ink starts right of
the text box, so the site can pull it back and every face shares one
visual left edge (brand/type-metrics.json, read by brand/src/css.ts)."""

import json
import statistics

import uharfbuzz as hb

LOWER = "abcdefghijklmnopqrstuvwxyz"
UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
DIGITS = "0123456789"


def left_bearing(face: hb.Face, axes: dict[str, float], chars: str) -> float:
    """The median left side bearing of `chars` at `axes`, in ems."""
    font = hb.Font(face)
    font.set_variations(axes)
    bearings = []
    for char in chars:
        glyph = font.get_nominal_glyph(ord(char))
        if glyph is None:
            continue
        bearings.append(font.get_glyph_extents(glyph).x_bearing / face.upem)
    return statistics.median(bearings)


def type_insets(faces: dict[str, bytes], tokens: dict) -> bytes:
    """Per role, the median left side bearing of the letters it sets: caps
    and figures for an uppercase role, else both cases."""
    hb_faces = {name: hb.Face(hb.Blob(data)) for name, data in faces.items()}
    insets = {}
    for name, role in tokens["type"].items():
        if name == "$type":
            continue
        value = role["$value"]
        extension = role["$extensions"]["dev.allthings"]
        face = "mono" if value["fontFamily"] == "{font.mono}" else "archivo"
        axes: dict[str, float] = {"wght": value["fontWeight"]}
        if face == "archivo":
            axes["wdth"] = float(extension.get("width", "100%").rstrip("%"))
        caps = extension.get("textTransform") == "uppercase"
        chars = UPPER + DIGITS if caps else LOWER + UPPER
        insets[name] = round(left_bearing(hb_faces[face], axes, chars), 4)
    document = {
        "$description": "Generated by brand/marks (metrics.py): each type role's median left side bearing, in ems, which the site's CSS pulls its text back by.",
        "inset": insets,
    }
    return (json.dumps(document, indent=2, sort_keys=True) + "\n").encode()
