name: Next.js App CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  test:
    name: 🧪 Tests
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🍞 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 📥 Download deps
        working-directory: app
        run: bun install

      - name: 💄 Format check
        working-directory: app
        run: bun run check

      - name: 🔍 Type check
        working-directory: app
        run: bun run typecheck
      - name: 🏄 Run the tests
        working-directory: app
        run: bun run test
