name: Generate Drizzle migrations on schema change

on:
  pull_request:
    paths:
      - 'app/src/lib/schema.ts'

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    # Only attempt to push commits when the PR branch is within the same repo
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies (app)
        working-directory: app
        run: bun install --frozen-lockfile

      - name: Generate Drizzle migrations
        working-directory: app
        env:
          # Drizzle config references DATABASE_URL, provide a dummy valid Postgres URL for config parsing
          DATABASE_URL: postgres://user:password@localhost:5432/db
        run: bun run db:generate

      - name: Commit and push migration diffs
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A app/migrations
          if ! git diff --staged --quiet; then
            git commit -m "chore(drizzle): update migrations from schema changes [skip ci]"
            git push
          else
            echo "No migration changes to commit."
          fi

